templates:
  template.yml:
    distributed:
      worker:
        event: default_evt
        events:
          default_evt:
            type: file
            value: distributed/worker/event.evt
      createNewFile:
        event: default_evt
        events:
          default_evt:
            type: file
            value: distributed/createNewFile/event.evt
      splitvideo:
        event: default_evt
        events:
          default_evt:
            type: file
            value: distributed/splitvideo/event.evt
    httpWorker:
      splitvideo:
        event: default_evt
        events:
          default_evt:
            type: file
            value: httpWorker/splitvideo/event.evt
