name: Pylint

on: 
  push:
    branches:
      - master



jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
        ref:switch-stack

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
